### PR TITLE
first map

### PR DESCRIPTION
**Pull request by minerva1993**
RPC map for report summary map normalization.

Related to the temporary PR for GUI https://github.com/dmwm/deployment/pull/1166

### CODE REVIEW

**Comment by minerva1993** [comment]
@iarspider @smuzaffar @aandvalenzuela 
Dear CMS-SDT members, I hope you are the right person to ask.
As far as I understood, if the file is merged, then during running cmssw for DQM, it will copy file to DQM/dataRPCMonitorClient/data, is it correct?
On the other words, can I safely test cmssw codes assuming the files are there?
Thanks in advance!

**_ps) Pleas don't merge the PR now, it will be updated most probably!_**

**Comment by iarspider** [comment]
@minerva1993 I believe you (or us) will need to make a PR to cmsdist to include this new data package.

**Comment by minerva1993** [comment]
> @minerva1993 I believe you (or us) will need to make a PR to cmsdist to include this new data package.

Thanks for quick reply! I believe [this link](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_5_X/master/data/cmsswdata.txt#L5) is the place to make a PR, right?

**Comment by iarspider** [comment]
@minerva1993 yes.

**Comment by minerva1993** [comment]
@iarspider Thanks! I'll make a PR once our changes are ready.

**Comment by smuzaffar** [comment]
@iarspider , @minerva1993 no need to open cmsdist PR. cms-bot knows how to add/test now data packages.
@minerva1993 let us know when this PR is ready for tests. By the way, is there any cms-sw/cmssw PR test this new data file?

**Comment by minerva1993** [comment]
@smuzaffar Hello, not really, we would like to test internally with further changes for now. We will let you know once ready. (by the way the code will be very straight forward, reason of delay is simply preparing 'good' data input file for RPC DQM.)

**Comment by smuzaffar** [comment]
ping , any update? should we keep this PR open?

**Comment by minerva1993** [comment]
> ping , any update? should we keep this PR open?

Hello, I moved to another institute which is not participating RPC, and this is not completed at the end. I think I can close the PR.

**Pull request closed without merging**
